### ISSUE TITLE
Not all movies are playable

### ISSUE THREAD

**Issue by Yeuxkes** [pietie/HyperSearch#8]
I have some systems where there's no preview available. All my movies are in mp4 format but for some reason not every movie is played back in Hypersearch, the preview screen shows up but doesn't play the movie.

**Comment by pietie** [comment]
What OS are you on?
Could you dropbox one of those mp4s for me?

**Comment by Yeuxkes** [comment]
I'm on Win 7 Ultimate x64

The following systems are affected, pretty much everything from nintendo:
NES, SNES, N64, GB, GBC, GBA, Famicom & Super Famicom but _Virtual Boy_ is
working
Sega: SMS, Genesis, 32x, SegaCD, Sega Model2, Triforce but _Game Gear_ is
working

The following systems are a bit weird
Capcom CPS 1 thru 3 were copied from MAME and do not work however the same
files play when MAME is selected
The same is true for Neo Geo MVS where I use a symbolic link from MAME's
directory to save on hard disk space.

... And this is when I had an eureka moment. For the systems that do not
work I have the video paths set in HyperHQ and I use relative paths.
For the systems that do work, I've only set em up recently and did not go
through all the HyperHQ settings yet, so the video path is blank.

So it seems that where the video path is blank in HyperHQ it's working.
(Mame also had no path set for some reason)
And after some testing now I found out the following, If I set
the absolute path then the movies play but it's a no go when I use relative
paths.
I didn't put much thought in it earlier because in Hyperspin/Hyperpause
everything is working, it was only when searching for the occasional game
thru your app that I noticed it.

I guess my problem for the movies not playing is solved, however I would
like to keep using relative paths if possible.

**Comment by pietie** [comment]
Relative paths are supported but are perhaps not working correctly.
Can you give me an example of a relative path you tried before?

**Comment by Yeuxkes** [comment]
My main Hyperspin is installed under D:\Emulators.Hyperspin
The path to my media folder is D:\Emulators.Hyperspin\Media
I have Hypersearch installed in D:\Emulators.HyperSpin\HyperSearch

In HyperHQ I have the following relative path set for the video folder
"..\Media\MAME\Video\"
This path works in Hyperspin and also for the Hyperpause part of
Rocketlauncher.

**Comment by pietie** [comment]
Edit: Oops. Turns out I do support that HyperHQ setting after all! Heh. I was just looking at old code. It does not seem to support relative paths though so I'll look into that

~~Ah okay...~~
~~The custom video path in HyperHQ is not currently supported.~~

~~The videos are hard-coded to look in **HyperSpin Path**\Media\**SystemName**\Video\**RomName**.mp4 (or flv)~~

~~So I'm not sure how making HyperHQ changes would affect it. It's mostly dependent on the HyperSpin path setting.~~

~~I'll look at adding support for the HyperHQ setting but can you please just confirm...is this the setting from video defaults? So if you open \Settings\MAME.ini for example, is it the **path** setting from [video_defaults]? My HyperHQ crashes when I try and make changes.~~

**Comment by pietie** [comment]
I'd appreciate it if you could try this beta version and see if it fixes this problem: [Download v2 Beta](https://dl.dropboxusercontent.com/u/59583314/HyperSearch%20v2%20Beta.7z)

**Comment by Yeuxkes** [comment]
Yup, relative paths are working now.

**Comment by pietie** [comment]
Awesome, thanks for the feedback
